language: node_js
node_js:
  - "lts/*"
before_script:
  - git remote set-branches --add origin gh-pages
  - git fetch origin gh-pages:gh-pages
  - git checkout gh-pages
script:
  - node index.js
  - node buildCaches.js
before_deploy:
  - rm -f deployed*
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
